### PR TITLE
6. Parser binder

### PR DESCRIPTION
**Pull request by huy-dna**
## Summary
* Add binder to DBML parser.
* Previous PR: #423 
* Implementation details: [Notion](https://www.notion.so/holistics/Analyzer-4bc8949df2744e198f7d287141a5e738)

## Issue
(issue link here)

## Lasting Changes (Technical)

(please list down: code changes/things that have wide-effect; new libraries/functions added that can be used by others; examples below)

* (Added `class EmailValidator` to validate email address' validity)
* (Added `Tenant#is_trial?` check)

## Checklist

Please check directly on the box once each of these are done

- [ ] Documentation (if necessary)
- [ ] Tests (integration test/unit test)
- [ ] Integration Tests Passed
- [ ] Code Review

### CODE REVIEW

**Comment by phuongduyphan** [comment]
Why adding a new `package-lock.json` at root em?

**Comment by phuongduyphan** [comment]
If you want to add/change sth related to validator, lexer, parser, I suggest you change in the corresponding PR. Changing all the things in one PR like this makes smaller PRs useless.

**Comment by phuongduyphan** [comment]
image

This error message is not clear when there are duplicated table names in schema.

**Comment by phuongduyphan** [comment]
This error message is ambiguous: 
image

**Comment by huy-dna** [comment]
> If you want to add/change sth related to validator, lexer, parser that not relevant to this binder, I suggest you change in the corresponding PR. Changing all the things in one PR like this makes breaking into smaller PRs useless.

Yeah, I'm well aware of that but pushing to the previous PRs would cause subsequent PRs that depend on them to break. Maybe I'm still inexperience at this.

**Comment by huy-dna** [comment]
> Why adding a new `package-lock.json` at root em?

This was my mistake.

**Comment by huy-dna** [comment]
> image
> 
> This error message is not clear when there are duplicated table names in schema.

Do you mean that the message should make it clear that where that name was previously defined?

**Pull request merged**
